**bold text**# New Section

# New Section

In [ ]:
### START CODE HERE ### (≈ 1 line of code)
test = "Hello World"
### END CODE HERE ###

In [ ]:
test

'Hello World'

In [ ]:
#is this saved in github
#testing again

#another test

In [1]:
import numpy as np

In [2]:
a = np.random.randn(2,3)
b = np.random.randn(2,1)
a
b

array([[ 1.42350211],
       [-1.50914057]])

In [3]:
a

array([[-0.2888944 , -0.1801103 , -0.20946359],
       [-0.31451526, -0.0533656 , -0.20959242]])

In [4]:
b

array([[ 1.42350211],
       [-1.50914057]])

In [5]:
a.dtype

dtype('float64')

In [6]:
c = a + b

In [7]:
c

array([[ 1.1346077 ,  1.2433918 ,  1.21403852],
       [-1.82365583, -1.56250617, -1.71873299]])

**Exercise**: Build a function that returns the sigmoid of a real number x. Use math.exp(x) for the exponential function.

In [2]:
import math

def basic_sigmoid(x):
  return 1/(1 + math.exp(-x))

In [3]:
basic_sigmoid(3)

0.9525741268224334

basic_sigmoid([1,2,3])

TypeError                                 Traceback (most recent call last)
<ipython-input-4-287735b76f00> in <cell line: 1>()
----> 1 basic_sigmoid([1,2,3])

<ipython-input-2-12730319b136> in basic_sigmoid(x)
      2
      3 def basic_sigmoid(x):
----> 4   return 1/(1 + math.exp(-x))

TypeError: bad operand type for unary -: 'list'


In [6]:
import numpy as np

x = np.array([1,2,3])
x

array([1, 2, 3])

In [7]:
def numpy_sigmoid(x):
  return 1/(1 + np.exp(-x))

In [12]:
numpy_sigmoid(np.array([1,2,3]))

array([0.73105858, 0.88079708, 0.95257413])

In [13]:
def sigmoid_derivative(x):
  return numpy_sigmoid(x)*(1-numpy_sigmoid(x))

In [14]:
sigmoid_derivative(np.array([1,2,3]))

array([0.19661193, 0.10499359, 0.04517666])

In [15]:
a = np.random.rand(2,3,4)

In [16]:
a.shape

(2, 3, 4)

In [19]:
len(a)

2

In [20]:
a.ndim

3

In [23]:
a.shape[0], a.shape[1], a.shape[2]

(2, 3, 4)

In [24]:
a.ndim

3

In [25]:
def image2vector(image):
  return image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)


In [26]:
a = np.array([1,2,3], ndmin=2)

In [27]:
a

array([[1, 2, 3]])

In [28]:
b = np.random.rand(2,3,4)

In [29]:
b

array([[[0.58009645, 0.87740049, 0.2053493 , 0.95812683],
        [0.17321477, 0.57228184, 0.27167129, 0.29022633],
        [0.39170196, 0.05919643, 0.77472122, 0.03526844]],

       [[0.80229703, 0.32264425, 0.97962916, 0.3618756 ],
        [0.43068446, 0.009022  , 0.25090631, 0.13836306],
        [0.213055  , 0.49312005, 0.28858371, 0.17125122]]])

In [30]:
image2vector(b)

array([[0.58009645],
       [0.87740049],
       [0.2053493 ],
       [0.95812683],
       [0.17321477],
       [0.57228184],
       [0.27167129],
       [0.29022633],
       [0.39170196],
       [0.05919643],
       [0.77472122],
       [0.03526844],
       [0.80229703],
       [0.32264425],
       [0.97962916],
       [0.3618756 ],
       [0.43068446],
       [0.009022  ],
       [0.25090631],
       [0.13836306],
       [0.213055  ],
       [0.49312005],
       [0.28858371],
       [0.17125122]])

In [31]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])


In [33]:
b = image2vector(image)

In [34]:
b.shape

(18, 1)

In [35]:
b[0]

array([0.67826139])

In [36]:
b[0][0]

0.67826139

In [51]:
def normalieRows(x):
  x_norm = np.linalg.norm(x, axis=1, keepdims=True)
  print(x_norm.shape)
  print(x_norm)
  x = x/x_norm
  return x

In [52]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])

In [53]:
normalieRows(x)

(2, 1)
[[5.        ]
 [7.28010989]]


array([[0.        , 0.6       , 0.8       ],
       [0.13736056, 0.82416338, 0.54944226]])

In [50]:
x.shape

(2, 3)

In [54]:
a = np.array([1,2,3])
b = np.exp(a)
b

array([ 2.71828183,  7.3890561 , 20.08553692])

In [68]:
a = np.random.randint(10, size=(2,3))


In [69]:
a

array([[4, 5, 0],
       [2, 9, 1]])

In [70]:
b = np.exp(a)
b

array([[5.45981500e+01, 1.48413159e+02, 1.00000000e+00],
       [7.38905610e+00, 8.10308393e+03, 2.71828183e+00]])

In [74]:
c = np.sum(a, axis=0, keepdims=True)
c

array([[ 6, 14,  1]])

In [75]:
d = np.sum(a, axis=1, keepdims=True)
d

array([[ 9],
       [12]])

In [76]:
c.shape

(1, 3)

In [77]:
c[0]

array([ 6, 14,  1])

In [80]:
def softmax(x):
  x_exp = np.exp(x)
  x_sum_exp = np.sum(x_exp, axis=1, keepdims=True)
  sm = x_exp/x_sum_exp
  return sm

In [82]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
y_hat = softmax(x)

In [83]:
y_hat

array([[9.80897665e-01, 8.94462891e-04, 1.79657674e-02, 1.21052389e-04,
        1.21052389e-04],
       [8.78679856e-01, 1.18916387e-01, 8.01252314e-04, 8.01252314e-04,
        8.01252314e-04]])

In [84]:
y_hat.sum(axis=1, keepdims=True)

array([[1.],
       [1.]])

In [85]:
a = np.random.randint(10, size=(2,3))

In [86]:
b = np.random.randint(10, size=(2,3))

In [87]:
a


array([[9, 7, 1],
       [7, 9, 2]])

In [88]:
b

array([[1, 1, 9],
       [4, 1, 9]])

In [90]:
dot = np.dot(a,b.T)

In [91]:
dot

array([[25, 52],
       [34, 55]])

In [92]:
sum(a)

array([16, 16,  3])

In [93]:
a - b

array([[ 8,  6, -8],
       [ 3,  8, -7]])

In [105]:
a = np.random.randint(10, size=(10,2))

In [106]:
a

array([[7, 4],
       [7, 2],
       [2, 7],
       [7, 0],
       [5, 3],
       [2, 6],
       [9, 0],
       [8, 0],
       [4, 8],
       [8, 4]])

In [107]:
b = np.random.randint(10, size=(10,2))

In [108]:
b

array([[1, 2],
       [6, 2],
       [9, 0],
       [3, 5],
       [7, 5],
       [4, 8],
       [1, 9],
       [6, 6],
       [9, 3],
       [1, 2]])

In [109]:
c = a - b
c

array([[ 6,  2],
       [ 1,  0],
       [-7,  7],
       [ 4, -5],
       [-2, -2],
       [-2, -2],
       [ 8, -9],
       [ 2, -6],
       [-5,  5],
       [ 7,  2]])

In [110]:
abs(c)

array([[6, 2],
       [1, 0],
       [7, 7],
       [4, 5],
       [2, 2],
       [2, 2],
       [8, 9],
       [2, 6],
       [5, 5],
       [7, 2]])

In [111]:
sum(abs(c))

array([44, 40])

In [116]:
np.sum(abs(c), axis=1)

array([ 8,  1, 14,  9,  4,  4, 17,  8, 10,  9])

In [117]:
def L1(yhat, y):
  return np.sum(abs(yhat - y))


In [118]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [119]:
def L2(yhat,y):
    return np.sum((yhat - y) ** 2)


In [120]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43


In [121]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
np.dot(a,b)

55

In [122]:
np.dot(a,b.T)

55